name: pytest

on:
  push:
    branches: [master]
  pull_request:

jobs:
  pytest:
    name: Run pytest
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.10"
            core-version: "2022.11.5"
          - python-version: "3.10"
            core-version: "2022.12.9"
          - python-version: "3.10"
            core-version: "2023.1.7"
          - python-version: "3.10"
            core-version: "2023.2.5"
          - python-version: "3.10"
            core-version: "2023.3.6"
          - python-version: "3.10"
            core-version: "2023.4.6"
          - python-version: "3.10"
            core-version: "2023.5.4"
          - python-version: "3.11"
            core-version: "2023.6.3"
          - python-version: "3.11"
            core-version: "2023.7.3"
          - python-version: "3.11"
            core-version: "2023.8.4"
          - python-version: "3.11"
            core-version: "2023.9.3"
          - python-version: "3.11"
            core-version: "2023.10.5"
          - python-version: "3.11"
            core-version: "2023.11.3"
          - python-version: "3.11"
            core-version: "2023.12.4"
          - python-version: "3.11"
            core-version: "2024.1.6"
          - python-version: "3.11"
            core-version: "2024.2.5"
          - python-version: "3.12"
            core-version: "2024.3.3"
          - python-version: "3.12"
            core-version: "2024.4.1"
          - python-version: "3.12"
            core-version: "dev"
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v3

      - name: Install Home Assistant
        uses: ./.github/workflows/install_dependencies
        with:
          python-version: ${{ matrix.python-version }}
          core-version: ${{ matrix.core-version }}

      - name: Run pytest
        timeout-minutes: 60
        run: |
          export PYTHONPATH=${PYTHONPATH}:${PWD}
          cd core
          python3 -X dev -m pytest \
            -vvv \
            -qq \
            --timeout=9 \
            --durations=10 \
            --cov="homeassistant/components/adaptive_lighting" \
            --cov-report=xml \
            --cov-report=html \
            -o console_output_style=count \
            -p no:sugar \
            tests/components/adaptive_lighting

      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.19
        with:
          reports: 'core/coverage.xml'
          targetdir: 'coveragereport'
          reporttypes: 'HtmlInline;Cobertura'
          assemblyfilters: '+*'
          classfilters: '+*'
          filefilters: '+*'
          verbosity: 'Info'
          tag: '${{ github.run_number }}_${{ github.run_id }}'

      - name: Push Coverage Report to Branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git checkout -B coverage-report
          mv coveragereport coverage-report
          git add coverage-report
          git commit -m "Update coverage report"
          git push -f origin coverage-report
